import re

file_path = r'c:\Users\Alan\OneDrive\Desktop\Japitown\game\tl\english\script\characters\violet\quests\violet_quest_04.rpy'
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

translations = [
    "Well, time to clean",
    "I don't know why I started cleaning this...",
    "I hope Raquel comes back soon",
    "Violet should be a little more careful when she eats here",
    "Living room is done. I'm going to see how Violet is doing.",
    "Are you still sweeping?",
    "We just started cleaning",
    "No, we started an hour ago...",
    "It was 5 minutes",
    "Did she fall asleep?",
    "She fell asleep",
    "Did you fall asleep while sweeping?",
    "How could I fall asleep sweeping?",
    "We need to hurry Violet, we have to finish before the girls come back",
    "Sorry",
    "At least she has a good temper when she's sleepy",
    "I'll help you, I'll stay up here, I'm going to find something to clean with",
    "Yes... thanks [mc_name]",
    "I'm going to the kitchen to find a mop",
    "One of these cabinets must have a mop",
    "Here it is",
    "One of these cabinets must have a mop",
    "{color=#FFFFFF}One cleaning session later{/color}",
    "I'm exhausted already, Violet should be done by now",
    "I'm going to see how she is",
    "Violet?",
    "Yes?",
    "What are you doing?",
    "I'm cleaning the bathroom",
    "Are you cleaning the bathroom rug with a cloth?",
    "I'm drying it, I spilled some water",
    "Half of her butt is in the air...",
    "Do you need something?",
    "I need to stop staring or this is going to be a problem",
    "No, I finished and wanted to see how you were doing",
    "Me too, help me up",
    "Ok",
    "Thanks [mc_name]",
    "It's weird to see her in this mood",
    "I could use this to improve our relationship a bit",
    "Is something wrong?",
    "No, why?",
    "You're staring at me without saying anything",
    "Shit, did she notice I was staring when she was bent over?",
    "I need to say something",
    "I was watching you clean",
    "I see...",
    "Ahh... I zoned out thinking",
    "About what?",
    "I hope I get used to it too",
    "To me being here?",
    "Yes...",
    "Don't be mean, you know we can get along if you cooperate",
    "Me cooperate?",
    "Yes you, ignoring me every chance you get",
    "I think you should cooperate in making up for all the time you disappeared",
    "You know I couldn't decide",
    "But you could communicate and you didn't, you didn't answer any more messages or anything",
    "And now you come acting the victim expecting everyone to say poor [mc_name]",
    "It's not like that",
    "Well it seems like it...",
    "I get your point and I'm going to try to change your mind",
    "Looks like the girls are back from shopping",
    "I'm going to help them bring the stuff in",
    "Running away again",
    "He was always scolding us to do things",
    "Yeah, or to go to sleep",
    "Or to stop screaming while playing video games hahaha",
    "Or for you to take a shower hahaha",
    "Yeah, or for you to take a shower",
    "I didn't have a problem taking a shower",
    "I remember something else",
    "Your memories are a bit distorted",
    "No, in all my memories we got along really well",
    "...",
    "Looks like the girls are back from shopping",
    "I'm going to help them bring the stuff in",
    "Me too",
    "What did you say?",
    "Hahaha my bad",
    "But it's the truth",
    "Have you become some kind of pervert now?",
    "It's your fault...",
    "My fault?",
    "It doesn't even cover half your butt",
    "And you know it's always been my favorite part",
    "I didn't do it on purpose, if it fits well on top it's too small on the bottom",
    "It's not my fault my body is disproportionate",
    "It looks perfect to me",
    "A little on top and a lot on the bottom",
    "Why did we end up talking about this?",
    "Ahh right, because you're a pervert",
    "I have my weaknesses",
    "Looks like the girls are back from shopping",
    "I'm going to help them bring the stuff in",
    "Weaknesses...?"
]

idx = 0
for i in range(len(lines)):
    if re.match(r'^\s+[a-z_]+ \"\"$', lines[i]):
        if idx < len(translations):
            lines[i] = lines[i].replace('""', f'"{translations[idx]}"')
            idx += 1

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f"Replaced {idx} empty translations.")
